import {
  Match,
  Alert,
  SimulationResult,
  Market,
} from "@/types";

export const mockMatch: Match = {
  id: "match-001",
  homeTeam: {
    id: "flamengo",
    name: "Flamengo",
    shortName: "FLA",
    logo: "🔴",
    color: "#E31D3C",
  },
  awayTeam: {
    id: "palmeiras",
    name: "Palmeiras",
    shortName: "PAL",
    logo: "🟢",
    color: "#006437",
  },
  homeScore: 1,
  awayScore: 1,
  minute: 67,
  status: "LIVE",
  competition: "Brasileirão Série A",
  stadium: "Maracanã",
  referee: "Anderson Daronco",
  weather: "⛅ Parcialmente Nublado",
  temperature: 24,
  attendance: 68420,
  stats: {
    possession: [58, 42],
    shots: [14, 8],
    shotsOnTarget: [6, 3],
    corners: [7, 4],
    fouls: [11, 14],
    yellowCards: [2, 3],
    redCards: [0, 0],
    attacks: [89, 61],
    dangerousAttacks: [42, 28],
    xG: [1.84, 0.96],
    xGA: [0.96, 1.84],
    bigChances: [4, 2],
  },
  odds: {
    homeWin: 1.95,
    draw: 3.40,
    awayWin: 4.10,
    over25: 1.72,
    under25: 2.08,
    btts: 1.88,
    bttsNo: 1.92,
  },
  ai: {
    score: 88,
    confidence: 82,
    favorite: "home",
    expectedValue: 12.4,
    trend: "Flamengo em crescimento. Pressão ofensiva aumentando nos últimos 15 minutos.",
    explanation:
      "A probabilidade de vitória do Flamengo aumentou de 61% para 79% porque houve crescimento do xG (1.84), aumento da pressão ofensiva (42 ataques perigosos), queda na posse adversária, 6 finalizações no gol nos últimos 15 minutos e substituições ofensivas recentes.",
    recommendation: "FORTE",
  },
  homePlayers: [
    {
      id: "p1",
      name: "Rossi",
      number: 1,
      position: "GK",
      teamId: "flamengo",
      stats: { goals: 0, assists: 0, shots: 0, shotsOnTarget: 0, passes: 28, passAccuracy: 89, keyPasses: 0, tackles: 1, interceptions: 2, fouls: 0, yellowCards: 0, redCards: 0, corners: 0, dribbles: 0, saves: 3, form: 85, avgRating: 7.2 },
    },
    {
      id: "p2",
      name: "Arrascaeta",
      number: 14,
      position: "MID",
      teamId: "flamengo",
      stats: { goals: 1, assists: 2, shots: 3, shotsOnTarget: 2, passes: 52, passAccuracy: 91, keyPasses: 4, tackles: 3, interceptions: 1, fouls: 2, yellowCards: 0, redCards: 0, corners: 2, dribbles: 5, form: 92, avgRating: 8.4, minutesPerGoal: 210 },
    },
    {
      id: "p3",
      name: "Pedro",
      number: 9,
      position: "FWD",
      teamId: "flamengo",
      stats: { goals: 2, assists: 1, shots: 5, shotsOnTarget: 3, passes: 22, passAccuracy: 78, keyPasses: 2, tackles: 1, interceptions: 0, fouls: 3, yellowCards: 1, redCards: 0, corners: 0, dribbles: 3, form: 88, avgRating: 8.1, minutesPerGoal: 180 },
    },
    {
      id: "p4",
      name: "Gerson",
      number: 8,
      position: "MID",
      teamId: "flamengo",
      stats: { goals: 0, assists: 1, shots: 1, shotsOnTarget: 0, passes: 48, passAccuracy: 87, keyPasses: 3, tackles: 5, interceptions: 3, fouls: 1, yellowCards: 1, redCards: 0, corners: 0, dribbles: 2, form: 80, avgRating: 7.6 },
    },
    {
      id: "p5",
      name: "Éverton Cebolinha",
      number: 11,
      position: "FWD",
      teamId: "flamengo",
      stats: { goals: 1, assists: 0, shots: 4, shotsOnTarget: 2, passes: 18, passAccuracy: 74, keyPasses: 1, tackles: 0, interceptions: 0, fouls: 1, yellowCards: 0, redCards: 0, corners: 3, dribbles: 6, form: 83, avgRating: 7.8, minutesPerGoal: 240 },
    },
  ],
  awayPlayers: [
    {
      id: "p10",
      name: "Weverton",
      number: 21,
      position: "GK",
      teamId: "palmeiras",
      stats: { goals: 0, assists: 0, shots: 0, shotsOnTarget: 0, passes: 22, passAccuracy: 85, keyPasses: 0, tackles: 0, interceptions: 1, fouls: 0, yellowCards: 0, redCards: 0, corners: 0, dribbles: 0, saves: 5, form: 84, avgRating: 7.4 },
    },
    {
      id: "p11",
      name: "Raphael Veiga",
      number: 23,
      position: "MID",
      teamId: "palmeiras",
      stats: { goals: 1, assists: 0, shots: 3, shotsOnTarget: 2, passes: 41, passAccuracy: 88, keyPasses: 3, tackles: 2, interceptions: 2, fouls: 2, yellowCards: 1, redCards: 0, corners: 1, dribbles: 3, form: 86, avgRating: 7.9, minutesPerGoal: 195 },
    },
    {
      id: "p12",
      name: "Endrick",
      number: 9,
      position: "FWD",
      teamId: "palmeiras",
      stats: { goals: 0, assists: 1, shots: 3, shotsOnTarget: 1, passes: 14, passAccuracy: 72, keyPasses: 1, tackles: 0, interceptions: 0, fouls: 2, yellowCards: 1, redCards: 0, corners: 0, dribbles: 4, form: 79, avgRating: 7.2 },
    },
    {
      id: "p13",
      name: "Zé Rafael",
      number: 8,
      position: "MID",
      teamId: "palmeiras",
      stats: { goals: 0, assists: 0, shots: 1, shotsOnTarget: 0, passes: 46, passAccuracy: 90, keyPasses: 2, tackles: 6, interceptions: 4, fouls: 3, yellowCards: 1, redCards: 0, corners: 0, dribbles: 1, form: 81, avgRating: 7.5 },
    },
    {
      id: "p14",
      name: "Dudu",
      number: 7,
      position: "FWD",
      teamId: "palmeiras",
      stats: { goals: 0, assists: 0, shots: 2, shotsOnTarget: 1, passes: 24, passAccuracy: 79, keyPasses: 1, tackles: 1, interceptions: 0, fouls: 1, yellowCards: 0, redCards: 0, corners: 2, dribbles: 4, form: 76, avgRating: 7.0 },
    },
  ],
  timeline: [
    { minute: 12, type: "corner", team: "home", player: "Éverton Cebolinha", description: "Escanteio" },
    { minute: 23, type: "goal", team: "home", player: "Pedro", description: "GOL! Pedro cabeceia após escanteio" },
    { minute: 34, type: "yellowCard", team: "away", player: "Zé Rafael", description: "Cartão amarelo - falta dura" },
    { minute: 41, type: "goal", team: "away", player: "Raphael Veiga", description: "GOL! Veiga de fora da área" },
    { minute: 45, type: "yellowCard", team: "home", player: "Gerson", description: "Cartão amarelo - reclamação" },
    { minute: 52, type: "corner", team: "home", player: "Éverton Cebolinha", description: "Escanteio" },
    { minute: 58, type: "yellowCard", team: "away", player: "Endrick", description: "Cartão amarelo - falta em Pedro" },
    { minute: 63, type: "corner", team: "away", player: "Dudu", description: "Escanteio" },
  ],
  momentumData: [
    { minute: 1, home: 50, away: 50, xGHome: 0, xGAway: 0 },
    { minute: 5, home: 55, away: 45, xGHome: 0.1, xGAway: 0 },
    { minute: 10, home: 58, away: 42, xGHome: 0.2, xGAway: 0.05 },
    { minute: 15, home: 52, away: 48, xGHome: 0.3, xGAway: 0.15 },
    { minute: 20, home: 62, away: 38, xGHome: 0.5, xGAway: 0.2 },
    { minute: 25, home: 70, away: 30, xGHome: 0.9, xGAway: 0.25 },
    { minute: 30, home: 55, away: 45, xGHome: 1.0, xGAway: 0.4 },
    { minute: 35, home: 48, away: 52, xGHome: 1.1, xGAway: 0.6 },
    { minute: 40, home: 45, away: 55, xGHome: 1.15, xGAway: 0.85 },
    { minute: 45, home: 50, away: 50, xGHome: 1.2, xGAway: 0.96 },
    { minute: 50, home: 54, away: 46, xGHome: 1.35, xGAway: 0.96 },
    { minute: 55, home: 60, away: 40, xGHome: 1.5, xGAway: 0.96 },
    { minute: 60, home: 65, away: 35, xGHome: 1.7, xGAway: 0.96 },
    { minute: 67, home: 68, away: 32, xGHome: 1.84, xGAway: 0.96 },
  ],
};

export const mockAlerts: Alert[] = [
  {
    id: "a1",
    type: "danger",
    emoji: "🚨",
    title: "Pressão extrema",
    description: "Flamengo com 5 ataques perigosos nos últimos 5 minutos",
    timestamp: "67'",
  },
  {
    id: "a2",
    type: "value",
    emoji: "💰",
    title: "Excelente entrada",
    description: "Over 2.5 ganhou valor — EV: +18.4% | Confiança: 84%",
    timestamp: "65'",
  },
  {
    id: "a3",
    type: "warning",
    emoji: "⚠️",
    title: "BTTS ganhou valor",
    description: "Ambas marcam: probabilidade subiu de 61% para 74%",
    timestamp: "63'",
  },
  {
    id: "a4",
    type: "info",
    emoji: "📊",
    title: "Escanteio próximo",
    description: "Padrão indica escanteio do Flamengo nos próximos 3 min",
    timestamp: "61'",
  },
  {
    id: "a5",
    type: "danger",
    emoji: "🚨",
    title: "Gol iminente",
    description: "xG do Flamengo: 1.84 | 4 grandes chances criadas",
    timestamp: "60'",
  },
];

export const mockResultMarkets: Market[] = [
  {
    name: "Vitória Flamengo",
    odds: 1.95,
    fairOdds: 1.82,
    preGameProb: 58,
    liveProb: 62,
    aiProb: 71,
    mathProb: 68,
    statProb: 66,
    mlProb: 73,
    expectedValue: 14.8,
    confidence: 82,
    risk: "BAIXO",
    explanation: "Flamengo dominando com xG de 1.84 contra 0.96. Pressão crescente nos últimos 15 min.",
    value: true,
  },
  {
    name: "Empate",
    odds: 3.40,
    fairOdds: 3.85,
    preGameProb: 26,
    liveProb: 22,
    aiProb: 18,
    mathProb: 20,
    statProb: 21,
    mlProb: 17,
    expectedValue: -8.2,
    confidence: 45,
    risk: "ALTO",
    explanation: "Empate pouco provável dado o domínio do Flamengo.",
    value: false,
  },
  {
    name: "Vitória Palmeiras",
    odds: 4.10,
    fairOdds: 5.20,
    preGameProb: 16,
    liveProb: 16,
    aiProb: 11,
    mathProb: 12,
    statProb: 13,
    mlProb: 10,
    expectedValue: -12.4,
    confidence: 30,
    risk: "ALTO",
    explanation: "Palmeiras com xG baixo e pressão defensiva alta.",
    value: false,
  },
  {
    name: "Dupla Chance 1X",
    odds: 1.28,
    fairOdds: 1.19,
    preGameProb: 84,
    liveProb: 84,
    aiProb: 89,
    mathProb: 88,
    statProb: 87,
    mlProb: 90,
    expectedValue: 6.8,
    confidence: 76,
    risk: "BAIXO",
    explanation: "Alta probabilidade combinada de vitória ou empate do Flamengo.",
    value: true,
  },
];

export const mockGoalMarkets: Market[] = [
  {
    name: "Over 1.5 Gols",
    odds: 1.22,
    fairOdds: 1.14,
    preGameProb: 78,
    liveProb: 96,
    aiProb: 97,
    mathProb: 96,
    statProb: 95,
    mlProb: 97,
    expectedValue: 4.2,
    confidence: 96,
    risk: "BAIXO",
    explanation: "Já há 2 gols marcados. Certeza quase absoluta.",
    value: true,
  },
  {
    name: "Over 2.5 Gols",
    odds: 1.72,
    fairOdds: 1.58,
    preGameProb: 52,
    liveProb: 68,
    aiProb: 74,
    mathProb: 72,
    statProb: 70,
    mlProb: 76,
    expectedValue: 18.4,
    confidence: 84,
    risk: "BAIXO",
    explanation: "xG combinado de 2.80. Alta chance de terceiro gol com 23 min restantes.",
    value: true,
  },
  {
    name: "Over 3.5 Gols",
    odds: 3.20,
    fairOdds: 3.40,
    preGameProb: 22,
    liveProb: 36,
    aiProb: 38,
    mathProb: 35,
    statProb: 34,
    mlProb: 39,
    expectedValue: -4.8,
    confidence: 58,
    risk: "MÉDIO",
    explanation: "Possível mas abaixo do valor justo.",
    value: false,
  },
  {
    name: "BTTS (Ambas marcam)",
    odds: 1.88,
    fairOdds: 1.74,
    preGameProb: 61,
    liveProb: 74,
    aiProb: 78,
    mathProb: 76,
    statProb: 75,
    mlProb: 79,
    expectedValue: 13.2,
    confidence: 78,
    risk: "BAIXO",
    explanation: "Ambos já marcaram. Alta probabilidade de manutenção.",
    value: true,
  },
  {
    name: "Próximo Gol Flamengo",
    odds: 1.65,
    fairOdds: 1.52,
    preGameProb: 58,
    liveProb: 65,
    aiProb: 72,
    mathProb: 70,
    statProb: 68,
    mlProb: 73,
    expectedValue: 12.8,
    confidence: 74,
    risk: "BAIXO",
    explanation: "Flamengo com maior probabilidade de marcar próximo gol baseado em xG e pressão.",
    value: true,
  },
];

export const mockCornerMarkets: Market[] = [
  {
    name: "Mais Escanteios Flamengo",
    odds: 1.75,
    fairOdds: 1.62,
    preGameProb: 55,
    liveProb: 68,
    aiProb: 72,
    mathProb: 70,
    statProb: 68,
    mlProb: 73,
    expectedValue: 10.4,
    confidence: 76,
    risk: "BAIXO",
    explanation: "Flamengo com 7 contra 4 escanteios.",
    value: true,
  },
  {
    name: "Over 9.5 Escanteios",
    odds: 2.10,
    fairOdds: 1.94,
    preGameProb: 44,
    liveProb: 58,
    aiProb: 64,
    mathProb: 62,
    statProb: 60,
    mlProb: 65,
    expectedValue: 8.8,
    confidence: 68,
    risk: "MÉDIO",
    explanation: "11 escanteios em 67 min. Taxa indica mais 3-4 escanteios restantes.",
    value: true,
  },
];

export const mockCardMarkets: Market[] = [
  {
    name: "Mais Cartões (Palmeiras)",
    odds: 1.90,
    fairOdds: 1.74,
    preGameProb: 48,
    liveProb: 62,
    aiProb: 68,
    mathProb: 66,
    statProb: 64,
    mlProb: 69,
    expectedValue: 9.4,
    confidence: 72,
    risk: "BAIXO",
    explanation: "Palmeiras com 3 cartões contra 2. Árbitro rigoroso com 11 faltas do Palmeiras.",
    value: true,
  },
  {
    name: "Over 4.5 Cartões",
    odds: 1.85,
    fairOdds: 1.72,
    preGameProb: 52,
    liveProb: 64,
    aiProb: 70,
    mathProb: 68,
    statProb: 66,
    mlProb: 71,
    expectedValue: 11.8,
    confidence: 74,
    risk: "MÉDIO",
    explanation: "5 cartões em 67 min. Alta tensão no jogo sugere mais cartões.",
    value: true,
  },
];

export const mockExactScores: { score: string; probability: number; change: number }[] = [
  { score: "2-1", probability: 18.4, change: 3.2 },
  { score: "1-1", probability: 14.2, change: -2.1 },
  { score: "2-2", probability: 11.8, change: 4.5 },
  { score: "3-1", probability: 10.6, change: 2.8 },
  { score: "2-0", probability: 8.4, change: -1.4 },
  { score: "3-2", probability: 7.2, change: 3.1 },
  { score: "1-2", probability: 6.8, change: -0.8 },
  { score: "4-1", probability: 5.4, change: 1.6 },
  { score: "3-0", probability: 4.8, change: -0.4 },
  { score: "4-2", probability: 3.6, change: 1.2 },
];

export const mockSimulationResults: SimulationResult[] = [
  { outcome: "Vitória Flamengo", probability: 71.2, count: 71200 },
  { outcome: "Empate", probability: 17.8, count: 17800 },
  { outcome: "Vitória Palmeiras", probability: 11.0, count: 11000 },
  { outcome: "Over 2.5 Gols", probability: 74.4, count: 74400 },
  { outcome: "BTTS", probability: 78.6, count: 78600 },
  { outcome: "Flamengo marca primeiro", probability: 65.2, count: 65200 },
];

export function getScoreLabel(score: number): { label: string; color: string } {
  if (score >= 90) return { label: "MUITO FORTE", color: "text-emerald-400" };
  if (score >= 80) return { label: "FORTE", color: "text-green-400" };
  if (score >= 70) return { label: "BOM", color: "text-yellow-400" };
  if (score >= 60) return { label: "MODERADO", color: "text-orange-400" };
  if (score >= 40) return { label: "FRACO", color: "text-red-400" };
  return { label: "EVITAR", color: "text-red-600" };
}
